#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define ENCODER_DIRECTION_FLIP

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CIRQUE_PINNACLE_TAP_ENABLE
#undef POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define PERMISSIVE_HOLD
#define TAPPING_TERM 200
